src/EmployeesManagement.Web/Pages/Employee/Index.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Threading.Tasks;
using EmployeeManagement.FileSystems;
using EmployeesManagement.Employees;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Volo.Abp.AspNetCore.Mvc.UI.RazorPages;

namespace EmployeesManagement.Web.Pages.Employees
{
    public class Index : AbpPageModel
    {
        // [BindProperty]
        // public UploadFileDto UploadFileDto { get; set; }

        // private readonly IFileAppService _fileAppService;
        [BindProperty]
        public UISaveEmployeeDto UISaveEmployeeDto { get; set; }

        private readonly IEmployeeAppService _employeeService;
        private readonly IFileSystemAppService _fileService;
        public bool Saved { get; set; } = false;

        public Index(IEmployeeAppService employeeAppService,  IFileSystemAppService fileService)
        {
            _employeeService = employeeAppService;
            _fileService = fileService;
        }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostAsync()
        {
            
            var employeeServiceInput =  String.IsNullOrEmpty(UISaveEmployeeDto.Name) ?
            new EmployeeInput() :
            new EmployeeInput()
            {
                //create main object here
                Name = UISaveEmployeeDto.Name,
            };

            using (var memoryStream = new MemoryStream())
            {

                #region  manage fiels
                if (UISaveEmployeeDto.ProfilePic != null)
                {
                    await UISaveEmployeeDto.ProfilePic.CopyToAsync(memoryStream);
                    var newFileObject = new FileObject
                    {
                        FileName = UISaveEmployeeDto.ProfilePic.FileName,
                        FileExtension = Path.GetExtension(UISaveEmployeeDto.ProfilePic.FileName),
                        FileSize = UISaveEmployeeDto.ProfilePic.Length / 1024, //convert from Byte to KB
                        FileSubject = FileSubjects.Profile,
                        FileTitle = "Employee Profile",
                        FileContent = memoryStream.ToArray()
                    };
                    employeeServiceInput.Files.Add(newFileObject);
                }

                if (UISaveEmployeeDto.Evidence1 != null)
                {
                    await UISaveEmployeeDto.Evidence1.CopyToAsync(memoryStream);
                    var newFileObject = new FileObject
                    {
                        FileName = UISaveEmployeeDto.Evidence1.FileName,
                        FileExtension = Path.GetExtension(UISaveEmployeeDto.Evidence1.FileName),
                        FileSize = UISaveEmployeeDto.Evidence1.Length / 1024, //convert from Byte to KB
                        FileSubject = FileSubjects.Evidence,
                        FileTitle = "Employee Evidence1",
                        FileContent = memoryStream.ToArray()
                    };
                    employeeServiceInput.Files.Add(newFileObject);
                }

                if (UISaveEmployeeDto.Evidence2 != null)
                {
                    await UISaveEmployeeDto.Evidence2.CopyToAsync(memoryStream);
                    var newFileObject = new FileObject
                    {
                        FileName = UISaveEmployeeDto.Evidence2.FileName,
                        FileExtension = Path.GetExtension(UISaveEmployeeDto.Evidence2.FileName),
                        FileSize = UISaveEmployeeDto.Evidence2.Length / 1024, //convert from Byte to KB
                        FileSubject = FileSubjects.Evidence,
                        FileTitle = "Employee Evidence2",
                        FileContent = memoryStream.ToArray()
                    };
                    employeeServiceInput.Files.Add(newFileObject);
                }
                #endregion


            }
            var blobContainer = await _employeeService.CreatingAsync(employeeServiceInput);
            return Page();
        }
        public async Task<IActionResult> OnPostDeleteContainer()
        {
            if(String.IsNullOrEmpty(UISaveEmployeeDto.Name)) return Page();
            _fileService.DeleteFilesAsync(UISaveEmployeeDto.Name);

            return Page();
        }

    }


    public class UISaveEmployeeDto
    {
       // [Required]
        [Display(Name = "File")]

        public IFormFile ProfilePic { get; set; }
        public IFormFile Evidence1 { get; set; }
        public IFormFile Evidence2 { get; set; }

       // [Required]
        [Display(Name = "Filename")]
        public string FileName { get; set; }
        public string Name { get; set; }
    }
    
}

src/EmployeesManagement.Web/Pages/Index.cshtml.cs
namespace EmployeesManagement.Web.Pages;

public class IndexModel : EmployeesManagementPageModel
{
    public void OnGet()
    {

    }
}

src/EmployeesManagement.Web/Pages/Employee/Index.cshtml
@page
@model EmployeesManagement.Web.Pages.Employees.Index

@section scripts{
@* <abp-script src="/Pages/Files/index.js" /> *@
}

<abp-card>
    <abp-card-header>
        <h3>File Upload and Download</h3>
    </abp-card-header>
    <abp-card-body>
        <abp-row>
            <abp-column>
                <h3>Upload File</h3>
                <hr />
                <form method="post" enctype="multipart/form-data">

                    <abp-input asp-for="UISaveEmployeeDto.Name"></abp-input>
                    <abp-input asp-for="UISaveEmployeeDto.ProfilePic"></abp-input>
                    <abp-input asp-for="UISaveEmployeeDto.Evidence1"></abp-input>
                    <abp-input asp-for="UISaveEmployeeDto.Evidence2"></abp-input>
                    <input type="submit" class="btn btn-info" />
                </form>

                <form asp-page="Index" asp-page-handler="DeleteContainer" enctype="multipart/form-data">
                    <h1>Delete Container</h1>
                    <abp-input asp-for="UISaveEmployeeDto.Name"></abp-input>
                    <input type="submit" class="btn btn-info" value="Delete Container"/>
                </form>
                
                @* <form  asp-page="Index" asp-page-handler="SaveFile" enctype="multipart/form-data">
                    <input type="submit" class="btn btn-info" value="Save files without employee"/>
                </form> *@
            </abp-column>

            @* <abp-column style="border-left: 1px dotted gray">
                <h3>Download File</h3>
                <hr />
                <form id="DownloadFile">
                <div class="form-group">
                <label for="fileName">Filename</label><span> * </span>
                <input type="text" id="fileName" name="fileName" class="form-control ">
                </div>

                <input type="submit" class="btn btn-info"/>
                </form>
                </abp-column> *@
        </abp-row>
    </abp-card-body>
</abp-card>

src/EmployeesManagement.Web/Pages/Index.cshtml
@page
@using Microsoft.AspNetCore.Mvc.Localization
@using EmployeesManagement.Localization
@using Volo.Abp.Users
@model EmployeesManagement.Web.Pages.IndexModel
@inject IHtmlLocalizer<EmployeesManagementResource> L
@inject ICurrentUser CurrentUser
@section styles {
    <abp-style src="/Pages/Index.css" />
}
@section scripts {
    <abp-script src="/Pages/Index.js" />
}
<div class="container">
    <div class="p-5 text-center">
        <div class="d-inline-block bg-success text-white p-1 h5 rounded mb-4 " role="alert">
            <h5 class="m-1"> <i class="fas fa-rocket"></i> Congratulations, <strong>EmployeesManagement</strong> is successfully running!</h5>
        </div>
        <h1>Welcome to the Application</h1>

        <p class="lead px-lg-5 mx-lg-5">@L["LongWelcomeMessage"]</p>

        @if (!CurrentUser.IsAuthenticated)
        {
            <a abp-button="Primary" href="~/Account/Login" ><i class="fa fa-sign-in"></i> @L["Login"]</a>
        }

    </div>
    <div class="my-3 text-center">
        <h3>Let's improve your application!</h3>
        <p>Here are some links to help you get started:</p>
    </div>
    <div class="card mt-4 mb-5">
        <div class="card-body">
            <div class="row text-center justify-content-md-center">
                <div class="col-lg-4">
                    <div class="p-4">
                        <h5 class="mb-3"><i class="fas fa-book text-secondary d-block my-3 fa-2x"></i> Learn the ABP Framework</h5>
                        <p>Explore the compherensive documentation to learn how to build a modern web application.</p>
                        <a href="https://docs.abp.io/en/abp/latest?ref=tmpl" target="_blank" class="btn btn-link px-1">See Documents <i class="fas fa-chevron-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-4 border-start">
                    <div class="p-4">
                        <h5 class="mb-3"><i class="fas fa-cubes text-secondary d-block my-3 fa-2x"></i> Samples</h5>
                        <p>See the example projects built with the ABP Framework.</p>
                        <a href="https://docs.abp.io/en/abp/latest/Samples/Index?ref=tmpl" target="_blank" class="btn btn-link px-1">All samples <i class="fas fa-chevron-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-4 border-start">
                    <div class="p-4">
                        <h5 class="mb-3"><i class="fas fa-users text-secondary d-block my-3 fa-2x"></i> ABP Community</h5>
                        <p>Get involved with a vibrant community and become a contributor.</p>
                        <a href="https://community.abp.io/" target="_blank" class="btn btn-link px-1">Community <i class="fas fa-chevron-right"></i></a>
                        <a href="https://docs.abp.io/en/abp/latest/Contribution/Index?ref=tmpl" target="_blank" class="btn btn-link px-1">Contribute <i class="fas fa-chevron-right"></i></a>
                    </div>
                </div>
            </div>
            <div class="row text-center mt-lg-3 justify-content-md-center">
                <div class="col-lg-4">
                    <div class="p-4">
                        <h5 class="mb-3"><i class="fas fa-pen-nib text-secondary d-block my-3 fa-2x"></i> ABP Blog</h5>
                        <p>Take a look at our recently published articles.</p>
                        <a href="https://blog.abp.io/abp?ref=tmpl" target="_blank" class="btn btn-link px-1">See Blog <i class="fas fa-chevron-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-4 border-start">
                    <div class="p-4">
                        <h5 class="mb-3"><i class="fab fa-github text-secondary d-block my-3 fa-2x"></i> Github</h5>
                        <p>Do you love the ABP Framework? Please <strong>give a star</strong> to support it!</p>
                        <p class="mb-1">
                            <a class="github-button" href="https://github.com/abpframework/abp" data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star abpframework/abp on GitHub">Star</a>
                            <a class="github-button" href="https://github.com/abpframework/abp/issues" data-icon="octicon-issue-opened" data-size="large" data-show-count="false" aria-label="Issue abpframework/abp on GitHub">Issue</a>
                            <a class="github-button" href="https://github.com/abpframework/abp/fork" data-icon="octicon-repo-forked" data-size="large" data-show-count="false" aria-label="Fork abpframework/abp on GitHub">Fork</a>
                        </p>
                        <a href="https://github.com/abpframework/abp/issues/new?template=feature.md" target="_blank" class="btn btn-link px-1">Request a feature <i class="fas fa-chevron-right"></i></a>
                        <script async defer src="https://buttons.github.io/buttons.js"></script>
                    </div>
                </div>
                <div class="col-lg-4 border-start">
                    <div class="p-4">
                        <h5 class="mb-3"><i class="fab fa-stack-overflow text-secondary d-block my-3 fa-2x"></i> Stackoverflow</h5>
                        <p>See answers to previously asked questions or ask a new one.</p>
                        <a href="https://stackoverflow.com/questions/tagged/abp" target="_blank" class="btn btn-link px-1">Questions <i class="fas fa-chevron-right"></i></a>
                        <a href="https://stackoverflow.com/questions/ask" target="_blank" class="btn btn-link px-1">Ask a Question <i class="fas fa-chevron-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-5 my-3 text-center">
        <h3>Meet the ABP Commercial</h3>
        <p>A Complete Web Application Platform Built on the ABP Framework</p>
    </div>

    <div class="card mt-4 mb-5">
        <div class="card-body">
            <p class="px-lg-5 mx-lg-5 py-3 text-center">
                <a href="https://commercial.abp.io/" target="_blank">ABP Commercial</a> is a platform based on the open source ABP framework. It provides pre-built application modules,
                rapid application development tooling, professional UI themes, premium support and more.
            </p>

            <div class="row text-center justify-content-md-center">
                <div class="col-lg-2">
                    <div class="p-3">
                        <h6>
                            <i class="fas fa-plus d-block mb-3 fa- 2x text-secondary"></i> Startup Templates
                            <a href="https://commercial.abp.io/startup-templates?ref=tmpl" target="_blank" class="d-block mt-2 btn btn-sm btn-link">Details <i class="fas fa-chevron-right"></i></a>
                        </h6>
                    </div>
                </div>
                <div class="col-lg-2 border-start">
                    <div class="p-3">
                        <h6>
                            <i class="fas fa-plus d-block mb-3 fa- 2x text-secondary"></i> Application Modules
                            <a href="https://commercial.abp.io/modules?ref=tmpl" target="_blank" class="d-block mt-2 btn btn-sm btn-link">Details <i class="fas fa-chevron-right"></i></a>
                        </h6>
                    </div>
                </div>
                <div class="col-lg-2 border-start">
                    <div class="p-3">
                        <h6>
                            <i class="fas fa-plus d-block mb-3 fa- 2x text-secondary"></i> Developer<br />Tools
                            <a href="https://commercial.abp.io/tools?ref=tmpl" target="_blank" class="d-block mt-2 btn btn-sm btn-link">Details <i class="fas fa-chevron-right"></i></a>
                        </h6>
                    </div>
                </div>
                <div class="col-lg-2 border-start">
                    <div class="p-3">
                        <h6>
                            <i class="fas fa-plus d-block mb-3 fa- 2x text-secondary"></i> UI<br /> Themes
                            <a href="https://commercial.abp.io/themes?ref=tmpl" target="_blank" class="d-block mt-2 btn btn-sm btn-link">Details <i class="fas fa-chevron-right"></i></a>
                        </h6>
                    </div>
                </div>
                <div class="col-lg-2 border-start">
                    <div class="p-3">
                        <h6>
                            <i class="fas fa-plus d-block mb-3 fa- 2x text-secondary"></i> Premium Support
                            <a href="https://support.abp.io/QA/Questions?ref=tmpl" target="_blank" class="d-block mt-2 btn btn-sm btn-link">Details <i class="fas fa-chevron-right"></i></a>
                        </h6>
                    </div>
                </div>
                <div class="col-lg-2 border-start">
                    <div class="p-3">
                        <h6>
                            <i class="fas fa-plus d-block mb-3 fa- 2x text-secondary"></i> Additional Services
                            <a href="https://commercial.abp.io/additional-services?ref=tmpl" target="_blank" class="d-block mt-2 btn btn-sm btn-link">Details <i class="fas fa-chevron-right"></i></a>
                        </h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mb-5 text-center">
        <p class="align-middle">
            <a href="https://twitter.com/abpframework" target="_blank" class="mx-2"><i class="fa fa-twitter"></i><span class="text-secondary"> Abp Framework</span></a>
            <a href="https://twitter.com/abpcommercial" target="_blank" class="mx-2"><i class="fa fa-twitter"></i><span class="text-secondary"> Abp Commercial</span></a>
            <a href="https://github.com/abpframework/abp" target="_blank" class="mx-2"><i class="fa fa-github"></i><span class="text-secondary"> abpframework</span></a>
        </p>
    </div>
</div>